  
export const FETCH_RESTURANTS_REQUEST = 'FETCH_RESTURANTS_REQUEST'
export const FETCH_RESTURANTS_SUCCESS = 'FETCH_RESTURANTS_SUCCESS'
export const FETCH_RESTURANTS_FAILURE = 'FETCH_RESTURANTS_FAILURE'
export const FETCH_CATAGORY_SUCCESS = 'FETCH_CATAGORY_SUCCESS'
export const POST_RESTURANTS_REQUEST = 'POST_RESTURANTS_REQUEST'
export const POST_RESTURANTS_SUCCESS = 'POST_RESTURANTS_SUCCESS'
export const POST_RESTURANTS_FAILURE = 'POST_RESTURANTS_FAILURE'
export const GRILL = 'GRILL'
export const PIZZA = 'PIZAA'
export const PASTA = 'PASTA'
export const THI_FOOD = 'THI_FOOD'
export const FISH = 'FISH'

